{
    "mariadb":{
        "host":"127.0.0.1",
        "port":3306,
        "user":"aaa",
        "password":"aaa",
        "database":"aaa",
        "charset":"utf8"
        },
    "localhost":{
        "host":"localhost",
        "port":3306,
        "user":"root",
        "password":"root",
        "database":"ifs_test1",
        "charset":"utf8"
        },
    "tidb":{
        "host":"127.0.0.1",
        "port":3306,
        "user":"ccc",
        "password":"ccc",
        "database":"ccc",
        "charset":"utf8"
        }
}
